### ISSUE TITLE
native_name(key) returns numbers, instead of language names

### ISSUE THREAD

**Issue by Horadrim** [getgrav/grav-plugin-langswitcher#10]
Hi, after updating to the new version, I`ve noticed that the native_name(key) function actually returnsnumbers, instead of proper language names:
https://i.gyazo.com/4a6539217d473cf8cf4337df972d28e2.png

So now native_name(key) returns the array keys as integers, instead of English, Bulgarian and so on.

**Comment by flaviocopes** [comment]
I tested with the latest `develop` branch. 

`{{native_name('en')}}`

returns **English**

Seems to work fine to me

**Comment by benyaminl** [comment]
Ah it same as me long ago, to fix this you need to change the template codes, Seems there's a code that's changing. see this #7 on my comment https://github.com/getgrav/grav-plugin-langswitcher/issues/7#issuecomment-222342989, nah you should change langskadjh.html.twig, i mean in your partials templates, Since No clear why, but for your problem it would fix it, the array is changging as I dump the variable. 

change it from here https://github.com/getgrav/grav-plugin-langswitcher/tree/develop/templates/partials and it should fix it @flaviocopes @Horadrim

**Comment by tidiview** [comment]
SEE SOLUTION NEXT POST
same problem with grav 1.1.1. after update of plugin langswitcher.
what would be a solution?
[1 + {{ lang_url ~ uri.params }} outputs /1 or /2 which is the position of the config language array where it should be /ja or /en,
2+ {{ native_name(key)|capitalize }} does not output anything, where it should be 日本語 or English.]
see below the output:

```
<li>
<a href="/1" class=" external"></a> 
</li>
<li>
<a href="/2" class=" external"></a>
</li>
```

note for complete information:
I have a multisite subdirectories setup
language settings of `system.yaml` are:

```
languages:
  supported:
     - fr
     - ja
     - en
  session_store_active: true     # Store active language in session
  http_accept_language: true   # Attempt to set the language based on http_accept_language header in the browser
  override_locale: true             # Override the default or system locale with language specific one
```

lagswitcher settings of `langswitcher.yaml` are:

```
enabled: true
built_in_css: false
```

Thanks in advance
