### ISSUE TITLE
Langswitcher.html.twig doesn't work properly with include_default_lang: false

### ISSUE THREAD

**Issue by rkrejcii** [getgrav/grav-plugin-langswitcher#12]
Is there any way please how to amend `langswitcher.html.twig` provided with the project so it will work when `include_default_lang` is set to `false`?

With `include_default_lang: true` it works properly.

But with `false` following problem happens:
- let's say that Grav site `www.gravsite.com` has two languages, `Italiano` set like a default and `English` set like a secondary.
- when user switches using the language switcher to `English` (so it starts to be default language), he can't switch back to `Italiano` anymore, because the switcher has following link set for `Italiano`: `www.gravsite.com` which redirects now to `www.gravsite.com/en`.
- the only way how to switch now to the Italian is to type directly the URL, such like `www.gravsite.com\it`, which returns switcher back to `Italiano`.
- the proper language switcher needed here should have language prefix in all URL's, also for the default language and should reflect the default language change

I tried to amend the provided Twig template, but didn't get any good result yet.

Here is my full config for languages:

```
languages:
  supported:
    - it
    - en
  include_default_lang: false
  translations: true
  translations_fallback: true
  session_store_active: true
  http_accept_language: false
  override_locale: false
```

Is there even any way how to do such amendment? Or the language switcher can be used only with all languages prefixed?

Thank you for any hint.

**Comment by flaviocopes** [comment]
In the case you set `include_default_lang: false`,  by turning off `session_store_active: false`, it works again as expected, I suggest you pick this route until we sort this out.

**Comment by rkrejcii** [comment]
Thank you for prompt reply @flaviocopes. So if I understand it well:

There is a need for a fix from your side to get the language switcher working properly with `include_default_lang: false`. Is that fix needed in the plugin or Grav's core? And is there any milestone/plan for that?

As far as I need to have `session_store_active` set to `true` (so users language switch will be reflected between tabs, windows and browser sessions),  I will for now use combination

```
include_default_lang: true
session_store_active: true
```

Is that OK for proper language switcher functionality or there is any catch I overlooked here?

Thanks.

**Comment by matthew-dean** [comment]
Thanks for the workaround. Can this bug be fixed?

**Comment by rhukster** [comment]
I'm checking this and it works fine for me with this configuration:

```
languages:
  supported:
    - en
    - de
    - es
    - fr
    - it
    - nb
    - nl
    - el
    - pl
    - zh-CN
    - zh-TW
  include_default_lang: false
  translations: true                        # Enable translations by default
  translations_fallback: true               # Fallback through supported translations if active lang doesn't exist
  session_store_active: false               # Store active language in session
  http_accept_language: false               # Attempt to set the language based on http_accept_language header in the browser
  override_locale: false 
```
