### ISSUE TITLE
this plugin not work with gravstrap-theme

### ISSUE THREAD

**Issue by ossplus** [getgrav/grav-plugin-langswitcher#13]
The plugin don't work with https://github.com/giansi/gravstrap-theme

https://github.com/giansi/gravstrap-theme/issues/20

**Comment by flaviocopes** [comment]
There should be nothing preventing this to work. Including `{% include 'partials/langswitcher.html.twig' %}` in the theme Twig should work out of the box.

Not sure how you implemented it in the theme.

**Comment by ossplus** [comment]
i added    

```
 {% if config.plugins.langswitcher.enabled %}
        {% include 'partials/langswitcher.html.twig' %}
    {% endif %}
```

to _footer_navigation.html.twig_ of the theme.    

the output is   

`<ul class="langswitcher"></ul>`

don't include the nav for language.

it seams the code in _langswitcher.html.twig_ have not run.

**Comment by flaviocopes** [comment]
Then it seems the site does not have any language defined, as inside that `<ul>` you should have the languages available. 

See https://learn.getgrav.org/content/multi-language#language-configuration

**Comment by flaviocopes** [comment]
Does it work with another theme?

**Comment by ossplus** [comment]
I added 

```
languages:
  supported:
    - en
    - zh
  include_default_lang: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: true
  override_locale: false
  home_redirect:
    include_lang: true
    include_route: false 
```

to `system.yaml`,
I can view the site with `http://url/zh` for one language, and `http://url` for one language, 
But i can't see the nav for languages (inside that `<ul>` don't have languages.) 

It seams the code inside `<ul>` of langswitcher.html.twig didn't run.

```
{% set langobj = grav['language'] %}

{% for key in langswitcher.languages %}

    {% if key == langswitcher.current %}

        {% set lang_url = page.url %}
        {% set active_class = ' active' %}
    {% else %}
        {% set lang_url = base_url_simple ~ langobj.getLanguageURLPrefix(key)~langswitcher.page_route ?: '/' %}
        {% set active_class = '' %}
    {% endif %}

    <li><a href="{{ lang_url ~ uri.params }}" class="external{{ active_class }}">{{  native_name(key)|capitalize }}</a></li>

{% endfor %}
```
