### ISSUE TITLE
No support for dash separated locales - en-US, zh-TW, zh-CN etc.

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-langswitcher#6]
So I added `zh-TW` but langswitcher doesn't show it in navigation. `zh` alone works so I suspect you cover a language but not all locales. Please add them too as I would like to have both Chinese Traditional (`zh-TW`) and Chinese Simplified (`zh-CN`) on my site.

**Comment by rhukster** [comment]
I'm not sure how this is possible.  It simply grabs the languages as they exist in the languages object:

https://github.com/getgrav/grav-plugin-langswitcher/blob/develop/langswitcher.php#L61

and then just loops over them:

https://github.com/getgrav/grav-plugin-langswitcher/blob/develop/templates/partials/langswitcher.html.twig#L4-L16

Can you add a `{{ dump(langobj) }}` in line 3 of langswitcher.html.twig?  You will need to turn on the debugger and the result should show up in the first 'messages' tab.

**Comment by ghost** [comment]
@rhukster thanks for quick reply - appreciate it! 
Here is log (pastebin):

http://pastebin.com/kqGKE8Bn

It looks like it's there but for some reason he doesn't display it on front-end. 
Its not just Chinese, my `en-us` which is default locale doesn't show up as well. I tried to wrap it in quotes "" and see whether it solves the problem but no difference. This is how it looks like currently in navigation on front-end - missing `en-us` and `zh-tw` - only Korean (`ko`) and Simplified Chinese (`zh`) are visible:

![screen shot 2016-05-29 at 1 54 26 am](https://cloud.githubusercontent.com/assets/4720153/15628901/5bfe6bd8-2540-11e6-99f9-23b010a8fca7.png)

**Comment by rhukster** [comment]
what does your `supported_languages` array look like in system.yaml ?

**Comment by ghost** [comment]
@rhukster first 17 lines of my _user/config/system.yaml_:

```
absolute_urls: false
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
languages:
  supported:
    - en-us
    - ko
    - zh
    - zh-tw
  include_default_lang: false
  translations: true
  translations_fallback: true
  session_store_active: true
  http_accept_language: true
  override_locale: true
```
